# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Retag image

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  packages: write

on:
  workflow_dispatch:
    inputs:
      old_tag:
        description: "Old tag from which images will be retagged to latest"
        required: true
        type: string

jobs:
  safeguard-timer:
    runs-on: ubuntu-latest
    if: inputs.old_tag != ''
    steps:
      - name: Safeguard wait
        env:
          SLEEP_TIME: "30"
        run: |
          echo "Triggered safeguard."
          echo "You have $SLEEP_TIME seconds to cancel the workflow if you want to cancel retagging."
          sleep $SLEEP_TIME

  retag-images:
    runs-on: ubuntu-latest
    needs: [safeguard-timer]
    if: inputs.old_tag != ''
    steps:
      - uses: Zeglius/ghcr-oci-retagger@3d5fa57743ba2a94b125317aee52f0daf8743d12
        with:
          GITHUB_TOKEN: ${{ github.token }}
          PREFIX: ghcr.io/
          TAG_MAPPINGS: |-
            ${{ github.repository }}:${{ inputs.old_tag }} => ${{ github.repository }}:latest
